### PR TITLE
Added a generic <T> parameter to GameState

### PR DESCRIPTION
**Pull request by iMplode-nZ**
I absolutely need to store data which can't easily be serialized into a byte array (and storing the state in a separate buffer just to work around the API is ridiculous). This PR has one possible implementation of generics that might be useful. (I guess I could add backwards compatibility by making the GameState T have a default of Vec<u8>, but I'd like to confirm that the owner of ggrs is interested in such changes before going through that)

This PR should not be merged because all the tests and examples are broken with it, which I'm planning to fix if people are interested in the modification.

### CODE REVIEW

**Comment by gschup** [comment]
Thank you for your PR! I really like the idea of a generic GameState. It has been on my to-do list for a long time, so I am very glad you picked it up :)

Putting the checksum generation behind a feature flag also seems like a good idea.

I would be very grateful if you could finalize the feature by fixing the examples and tests. Let me know if you need anything!

**Comment by gschup** [comment]
Regarding backwards compatibility: I don't think you need to care about it too much, we are 0.X. breaking changes are to be expected!

**Comment by iMplode-nZ** [comment]
Alright, I'll do that.

**Comment by iMplode-nZ** [comment]
Did that now.

**Pull request merged**
